Block: Block = "{" <items: (<BlockItem>)*> "}" => Block { <> };

BlockItem: BlockItem = {
  Decl => BlockItem::Decl(<>),
  Stmt => BlockItem::Stmt(<>),
}

Stmt: Stmt = {
  <lval: LVal> "=" <exp: Exp> ";" => Stmt::Assign(Assign{ <> }),
  <block: Block> => Stmt::Sblock(Sblock{ <> }),
  "if" "(" <exp: Exp> ")" <then_block: Block> <else_block: ("else" <Block>)?> => Stmt::If(If{ <> }),
  "return" <exp: Exp> ";" => Stmt::Return(Return{ <> }),
}
